version: 2
jobs:
  build-and-test:
    working_directory: ~/app
    docker:
    - image: circleci/mongo:3
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        command: 'sudo yarn install'
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
    - run:
        name: Run Typescript
        command: 'yarn build-ts'
    - run:
        name: Run Typescript lint
        command: 'yarn tslint'
    - run:
        name: Run tests
        command: 'yarn test'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
